name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bitcoin-version: ['BITCOINVER=0.21.0', 'BITCOINVER=0.19.1', 'BITCOINVER=24.0']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        push: false
        tags: ${{ steps.prep.outputs.tagged_image }}
        build-args: ${{ matrix.bitcoin-version }}
